adding relation controller to user for clusters for search box
initbiz/cumuluscore-plugin pull request #42
Opened 2021-08-12 11:59 UTC by djudzinski

2021-08-17 14:48 UTC, dzapek requested changes

2021-08-17 14:48 UTC, dzapek commented on eventhandlers/RainlabUserHandler.php
> +            if ($widget->getController() instanceof Users && $widget->model instanceof User) {
check this

2021-09-07 14:57 UTC, dzapek approved these changes

2021-09-07 15:25 UTC, tomaszstrojny reviewed
Looks good, although take a look at those two comments.

2021-09-07 15:25 UTC, tomaszstrojny commented on eventhandlers/RainlabUserHandler.php
> +                return $model->surname . ' ' . $model->name;
Full name should be in `first name last name` format.

2021-09-07 15:25 UTC, tomaszstrojny commented on models/cluster/related_columns.yaml
> +        searchable: true
Are you sure that `searchable` and `sortable` will work for related fields?

2021-09-07 16:19 UTC, closed without merging